import type { PersistedState } from "./types.js";

export const seedState: PersistedState = {
  elements: [
    {
      id: "cap-customer-management",
      name: "Customer Management",
      type: "Business Capability",
      layer: "Business",
      description: "Manage customer profiles, interactions, and service context.",
      risk: "medium",
      cost: 120000,
      status: "active",
      startDate: "2024-01-01",
      endOfLifeDate: "2029-12-31",
      customAttributes: { owner: "Sales Operations", maturity: "managed" },
      position: { x: 80, y: 80 }
    },
    {
      id: "cap-order-management",
      name: "Order Management",
      type: "Business Capability",
      layer: "Business",
      description: "Capture, validate, and orchestrate customer orders.",
      risk: "high",
      cost: 180000,
      status: "active",
      startDate: "2023-06-01",
      endOfLifeDate: "2028-12-31",
      customAttributes: { owner: "Commerce", criticality: "high" },
      position: { x: 360, y: 80 }
    },
    {
      id: "cap-billing",
      name: "Billing",
      type: "Business Capability",
      layer: "Business",
      description: "Generate invoices and manage billing events.",
      risk: "medium",
      cost: 140000,
      status: "active",
      startDate: "2024-03-01",
      endOfLifeDate: "2030-01-31",
      customAttributes: { owner: "Finance", compliance: "SOX relevant" },
      position: { x: 640, y: 80 }
    },
    {
      id: "proc-customer-onboarding",
      name: "Customer Onboarding",
      type: "Business Process",
      layer: "Business",
      description: "Process for creating a new customer and enabling commerce access.",
      risk: "low",
      cost: 65000,
      status: "active",
      startDate: "2024-02-01",
      endOfLifeDate: "2027-12-31",
      customAttributes: { frequency: "daily" },
      position: { x: 120, y: 260 }
    },
    {
      id: "proc-order-to-cash",
      name: "Order to Cash",
      type: "Business Process",
      layer: "Business",
      description: "End-to-end order fulfillment and invoice creation.",
      risk: "high",
      cost: 220000,
      status: "active",
      startDate: "2023-01-15",
      endOfLifeDate: "2028-06-30",
      customAttributes: { frequency: "continuous" },
      position: { x: 470, y: 260 }
    },
    {
      id: "app-crm-system",
      name: "CRM System",
      type: "Application Component",
      layer: "Application",
      description: "Primary application for customer records and customer interaction history.",
      risk: "medium",
      cost: 95000,
      status: "active",
      startDate: "2022-04-01",
      endOfLifeDate: "2027-04-01",
      customAttributes: { vendor: "FictionalCRM" },
      position: { x: 120, y: 460 }
    },
    {
      id: "app-erp-system",
      name: "ERP System",
      type: "Application Component",
      layer: "Application",
      description: "Core ERP for order, stock, and financial integration.",
      risk: "high",
      cost: 260000,
      status: "deprecated",
      startDate: "2020-01-01",
      endOfLifeDate: "2026-12-31",
      customAttributes: { vendor: "LegacyERP" },
      position: { x: 420, y: 460 }
    },
    {
      id: "app-billing-service",
      name: "Billing Service",
      type: "Application Component",
      layer: "Application",
      description: "Service responsible for invoice calculation and billing events.",
      risk: "medium",
      cost: 110000,
      status: "planned",
      startDate: "2025-01-01",
      endOfLifeDate: "2031-01-01",
      customAttributes: { runtime: "container" },
      position: { x: 700, y: 460 }
    },
    {
      id: "data-customer-data",
      name: "Customer Data",
      type: "Data Object",
      layer: "Data",
      description: "Customer master data and contact preferences.",
      risk: "high",
      cost: 55000,
      status: "active",
      startDate: "2022-04-01",
      endOfLifeDate: "2030-12-31",
      customAttributes: { classification: "personal data" },
      position: { x: 180, y: 660 }
    },
    {
      id: "data-invoice-data",
      name: "Invoice Data",
      type: "Data Object",
      layer: "Data",
      description: "Invoice documents, billing line items, and payment references.",
      risk: "medium",
      cost: 48000,
      status: "active",
      startDate: "2023-01-01",
      endOfLifeDate: "2032-12-31",
      customAttributes: { retention: "10 years" },
      position: { x: 560, y: 660 }
    },
    {
      id: "tech-cloud-runtime",
      name: "Cloud Runtime",
      type: "Technology Node",
      layer: "Technology",
      description: "Managed runtime for web services and integration workloads.",
      risk: "low",
      cost: 75000,
      status: "active",
      startDate: "2023-09-01",
      endOfLifeDate: "2033-12-31",
      customAttributes: { region: "eu-central" },
      position: { x: 250, y: 840 }
    },
    {
      id: "tech-database-cluster",
      name: "Database Cluster",
      type: "Technology Node",
      layer: "Technology",
      description: "Shared database cluster for operational data stores.",
      risk: "medium",
      cost: 125000,
      status: "active",
      startDate: "2021-01-01",
      endOfLifeDate: "2028-01-01",
      customAttributes: { engine: "PostgreSQL compatible" },
      position: { x: 590, y: 840 }
    }
  ],
  relations: [
    { id: "rel-1", source: "proc-customer-onboarding", target: "cap-customer-management", type: "realizes", description: "Onboarding contributes to customer management." },
    { id: "rel-2", source: "proc-order-to-cash", target: "cap-order-management", type: "realizes", description: "Order to cash realizes order management." },
    { id: "rel-3", source: "proc-order-to-cash", target: "cap-billing", type: "realizes", description: "Order to cash realizes billing." },
    { id: "rel-4", source: "app-crm-system", target: "proc-customer-onboarding", type: "serves", description: "CRM supports onboarding." },
    { id: "rel-5", source: "app-erp-system", target: "proc-order-to-cash", type: "serves", description: "ERP supports order to cash." },
    { id: "rel-6", source: "app-billing-service", target: "proc-order-to-cash", type: "serves", description: "Billing service supports invoice steps." },
    { id: "rel-7", source: "app-crm-system", target: "data-customer-data", type: "uses", description: "CRM uses customer data." },
    { id: "rel-8", source: "app-billing-service", target: "data-invoice-data", type: "uses", description: "Billing service writes invoice data." },
    { id: "rel-9", source: "app-erp-system", target: "data-invoice-data", type: "uses", description: "ERP consumes invoice data." },
    { id: "rel-10", source: "app-billing-service", target: "app-erp-system", type: "depends_on", description: "Billing service depends on ERP order context." },
    { id: "rel-11", source: "app-crm-system", target: "tech-cloud-runtime", type: "depends_on", description: "CRM runs on cloud runtime." },
    { id: "rel-12", source: "data-invoice-data", target: "tech-database-cluster", type: "depends_on", description: "Invoice data is stored on the database cluster." }
  ],
  auditLog: []
};
